dependencies:
  Brotli: 1.1.0
  Deprecated: 1.2.18
  GitPython: 3.1.44
  Mako: 1.3.9
  Markdown: '3.6'
  MarkupSafe: 3.0.2
  PyHive: 0.7.0
  PyNaCl: 1.5.0
  PyQt5: 5.15.10
  PyQt5-sip: 12.13.0
  PySocks: 1.7.1
  PyYAML: 6.0.2
  SQLAlchemy: 1.4.54
  TPOT: 0.12.2
  adagio: 0.2.6
  aiohappyeyeballs: 2.6.1
  aiohttp: 3.11.15
  aiosignal: 1.3.2
  alabaster: 1.0.0
  alembic: 1.15.2
  annotated-types: 0.7.0
  anyio: 4.9.0
  appdirs: 1.4.4
  asttokens: 3.0.0
  attrs: 25.3.0
  autocommand: 2.2.2
  babel: 2.17.0
  backports.tarfile: 1.2.0
  bcrypt: 4.3.0
  blinker: 1.9.0
  bokeh: 3.7.2
  branca: 0.8.1
  cachetools: 5.5.2
  certifi: 2025.1.31
  cffi: 1.17.1
  cfgv: 3.3.1
  charset-normalizer: 3.4.1
  click: 8.1.8
  cloudpickle: 3.1.1
  colorama: 0.4.6
  comm: 0.2.2
  contourpy: 1.3.1
  coverage: 7.8.0
  cryptography: 44.0.2
  cycler: 0.12.1
  cytoolz: 1.0.1
  dask: 2025.3.0
  dask-geopandas: 0.4.3
  databricks-sdk: 0.49.0
  deap: 1.4.2
  debugpy: 1.8.12
  decorator: 5.1.1
  distlib: 0.3.9
  distributed: 2025.3.0
  dnspython: 2.7.0
  docker: 7.1.0
  docutils: 0.21.2
  email-validator: 2.2.0
  exceptiongroup: 1.2.2
  execnet: 2.1.1
  executing: 2.2.0
  fastapi: 0.115.12
  fastapi-cli: 0.0.7
  filelock: 3.18.0
  flask: 3.1.0
  folium: 0.19.5
  fonttools: 4.56.0
  frozenlist: 1.5.0
  fs: 2.4.16
  fsspec: 2025.3.2
  fugue: 0.9.1
  future: 1.0.0
  geopandas: 1.0.1
  gitdb: 4.0.12
  google-auth: 2.38.0
  graphene: 3.4.3
  graphql-core: 3.2.6
  graphql-relay: 3.2.0
  greenlet: 3.1.1
  h11: 0.14.0
  h2: 4.2.0
  hpack: 4.1.0
  httpcore: 1.0.7
  httptools: 0.6.4
  httpx: 0.28.1
  hyperframe: 6.1.0
  identify: 2.6.9
  idna: '3.10'
  imagesize: 1.4.1
  importlib-metadata: 8.6.1
  importlib-resources: 6.5.2
  inflect: 7.3.1
  iniconfig: 2.0.0
  intake: 2.0.8
  ipykernel: 6.29.5
  ipython: 8.31.0
  itsdangerous: 2.2.0
  jaraco.collections: 5.1.0
  jaraco.context: 5.3.0
  jaraco.functools: 4.0.1
  jaraco.text: 3.12.1
  jedi: 0.19.2
  jinja2: 3.1.6
  joblib: 1.4.2
  jpype1: 1.5.2
  jsonschema: 4.23.0
  jsonschema-specifications: 2024.10.1
  jupyter-client: 8.6.3
  jupyter-core: 5.7.2
  kiwisolver: 1.4.7
  lightgbm: 4.6.0
  locket: 1.0.0
  lz4: 4.3.3
  mapclassify: 2.8.1
  markdown-it-py: 3.0.0
  matplotlib: 3.10.1
  matplotlib-inline: 0.1.7
  maturin: 1.8.3
  mdurl: 0.1.2
  mlflow: 2.21.2
  mlflow-skinny: 2.21.2
  mock: 5.2.0
  more-itertools: 10.3.0
  msgpack: 1.1.0
  multidict: 6.2.0
  munkres: 1.1.4
  narwhals: 1.33.0
  nest-asyncio: 1.6.0
  networkx: 3.4.2
  nodeenv: 1.9.1
  numpy: 2.2.4
  opentelemetry-api: 1.31.1
  opentelemetry-sdk: 1.31.1
  opentelemetry-semantic-conventions: 0.52b1
  packaging: '24.2'
  pandas: 2.2.3
  paramiko: 3.5.1
  parso: 0.8.4
  partd: 1.4.2
  pillow: 11.1.0
  pip: 25.0.1
  pkgutil-resolve-name: 1.3.10
  platformdirs: 4.3.6
  pluggy: 1.5.0
  ply: '3.11'
  pre-commit: 4.2.0
  prometheus-client: 0.21.1
  prometheus-flask-exporter: 0.23.2
  prompt-toolkit: 3.0.50
  propcache: 0.2.1
  protobuf: 5.29.3
  psutil: 6.1.1
  psycopg2: 2.9.9
  pure-sasl: 0.6.2
  pyOpenSSL: 25.0.0
  pyarrow: 19.0.1
  pyasn1: 0.6.1
  pyasn1-modules: 0.4.2
  pycparser: '2.22'
  pydantic: 2.11.1
  pydantic-core: 2.33.0
  pygments: 2.19.1
  pyogrio: 0.10.0
  pyparsing: 3.2.3
  pyproj: 3.7.1
  pytest: 8.3.5
  pytest-cov: 6.0.0
  pytest-rerunfailures: '15.0'
  pytest-xdist: 3.6.1
  python-dateutil: 2.9.0.post0
  python-dotenv: 1.1.0
  python-multipart: 0.0.20
  pytz: '2024.1'
  pyu2f: 0.1.5
  pywin32: '307'
  querystring-parser: 1.2.4
  referencing: 0.36.2
  requests: 2.32.3
  rich: 14.0.0
  rich-toolkit: 0.11.3
  roman-numerals-py: 3.1.0
  rpds-py: 0.24.0
  rsa: 4.9.1
  scikit-learn: 1.6.1
  scipy: 1.15.2
  semantic-version: 2.10.0
  setuptools: 75.8.2
  setuptools-rust: 1.11.0
  shapely: 2.0.7
  shellingham: 1.5.4
  sip: 6.7.12
  six: 1.17.0
  smmap: 5.0.2
  sniffio: 1.3.1
  snowballstemmer: 2.2.0
  sortedcontainers: 2.4.0
  sphinx: 8.2.3
  sphinxcontrib-applehelp: 2.0.0
  sphinxcontrib-devhelp: 2.0.0
  sphinxcontrib-htmlhelp: 2.1.0
  sphinxcontrib-jsmath: 1.0.1
  sphinxcontrib-qthelp: 2.0.0
  sphinxcontrib-serializinghtml: 1.1.10
  sql-metadata: 2.15.0
  sqlparse: 0.5.3
  stack-data: 0.6.3
  starlette: 0.46.1
  stopit: 1.1.2
  tblib: 3.1.0
  threadpoolctl: 3.6.0
  thrift: 0.20.0
  thrift-sasl: 0.4.3
  toml: 0.10.2
  tomli: 2.2.1
  toolz: 1.0.0
  tornado: 6.4.2
  tqdm: 4.67.1
  triad: 0.9.8
  typeguard: 4.3.0
  typer: 0.15.2
  typer-slim: 0.15.2
  typing-extensions: 4.13.0
  typing-inspection: 0.4.0
  tzdata: '2025.2'
  tzlocal: '5.3'
  ukkonen: 1.0.1
  update-checker: 0.18.0
  urllib3: 2.3.0
  uvicorn: 0.34.0
  virtualenv: 20.30.0
  waitress: 3.0.2
  watchfiles: 0.24.0
  wcwidth: 0.2.13
  websocket-client: 1.8.0
  websockets: 15.0.1
  werkzeug: 3.1.3
  wheel: 0.43.0
  win-inet-pton: 1.1.0
  wrapt: 1.17.2
  xgboost: 2.1.4
  xyzservices: 2025.1.0
  yarl: 1.18.3
  zict: 3.0.0
  zipp: 3.21.0
  zstandard: 0.23.0
